remote_user: "lxo"
remote_ip: "129.215.117.145"
remote_directory: "/recorded_datasets/edinburgh"
cloud_upload_directory: "/mnt/vdb/data"
clean_up: false
upload_attempts: 3
mcap_path: "/home/lxo/mcap"
parallel_processes: 5
