name: Reusable pre-commit
# The pre-commit configuration is in .pre-commit-config.yaml
# OG author: Christoph Fröhlich <christoph.froehlich@ait.ac.at>[ROS2 Control CI]
# UoE editor: Alejandro Bordallo <alex.bordallo@ed.ac.uk>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS2 distribution name'
        required: true
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: ros:${{ inputs.ros_distro }}
    env:
      # this will be src/{repo-owner}/{repo-name}
      path: src/${{ github.repository }}
    steps:
      - name: "Fix ROS expired signing key"
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list \
            && sudo rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg
          sudo apt-get update \
            && sudo apt-get install -y ca-certificates curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest \
            | grep -F "tag_name" \
            | awk -F\" '{print $4}'); \
          curl -L -s -o /tmp/ros2-apt-source.deb \
            "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
            && sudo apt-get update \
            && sudo apt-get install -y /tmp/ros2-apt-source.deb \
            && rm -f /tmp/ros2-apt-source.deb

      - name: "Determine prerequisites"
        id: prereq
        run: |
          command -v sudo >/dev/null 2>&1 || (apt update && apt install -y sudo)
          sudo apt update
          echo "need_node=$(command -v node >/dev/null 2>&1 && echo 0 || echo 1)" >> $GITHUB_OUTPUT
          echo "need_ros2=$(if [ -d "/opt/ros/${{ inputs.ros_distro }}" ]; then echo 0; else echo 1; fi)" \
          >> $GITHUB_OUTPUT

      # needed for github actions, and only if a bare ubuntu image is used
      - uses: actions/setup-node@v4
        if: ${{ steps.prereq.outputs.need_node == '1' && !env.ACT }}
      - name: Install node
        # Consider switching to https://github.com/actions/setup-node when it works
        # https://github.com/nektos/act/issues/973
        if: ${{ steps.prereq.outputs.need_node == '1' && env.ACT }}
        run: |
          sudo apt install -y curl
          curl -sS https://webi.sh/node | sh
          echo ~/.local/opt/node/bin >> $GITHUB_PATH

      # needed only if a non-ros image is used
      - uses: ros-tooling/setup-ros@0.7.10
        if: ${{ steps.prereq.outputs.need_ros2 == '1' }}
        with:
          use-ros2-testing: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.path }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ inputs.ros_distro }}|${{ hashFiles( format('{0}/.pre-commit-config.yaml', env.path) ) }}
      - name: Install pre-commit and system hooks
        shell: bash
        run: |
          sudo apt-get install -qq \
          ros-${{ inputs.ros_distro }}-ament-cppcheck \
          ros-${{ inputs.ros_distro }}-ament-cpplint \
          ros-${{ inputs.ros_distro }}-ament-lint-cmake \
          ros-${{ inputs.ros_distro }}-ament-copyright \
          python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install pre-commit
      - name: Run pre-commit
        shell: bash
        run: |
          source .venv/bin/activate
          source /opt/ros/${{ inputs.ros_distro }}/setup.bash
          cd ${{ env.path }}
          pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual
